### ISSUE TITLE
Compilation fails on armv6hf with ghc-7.4.1 (Template Haskell bracket illegal in a stage-1 compiler)

### ISSUE THREAD

**Issue by gohai** [sebastiaanvisser/fclabels#25]
Resolving dependencies...
Configuring fclabels-2.0.2.2...
Building fclabels-2.0.2.2...
Preprocessing library fclabels-2.0.2.2...
[ 1 of 10] Compiling Data.Label.Point ( src/Data/Label/Point.hs, dist/build/Data/Label/Point.o )
[ 2 of 10] Compiling Data.Label.Poly  ( src/Data/Label/Poly.hs, dist/build/Data/Label/Poly.o )
[ 3 of 10] Compiling Data.Label.Mono  ( src/Data/Label/Mono.hs, dist/build/Data/Label/Mono.o )
[ 4 of 10] Compiling Data.Label.Derive ( src/Data/Label/Derive.hs, dist/build/Data/Label/Derive.o )

src/Data/Label/Derive.hs:379:25:
    Template Haskell bracket illegal in a stage-1 compiler
      [| failArrow |]

src/Data/Label/Derive.hs:380:25:
    Template Haskell bracket illegal in a stage-1 compiler
      [| zeroArrow |]

Is this expected? I installed Haskell through the haskell-platform package.

**Comment by ndmitchell** [comment]
Note that this error isn't really a "GHC is too old", but in fact an error that GHC was built without a version of ghci, which is required to execute template haskell splices. A newer compiler would still have the same issue if built in the same way - and I'm not sure if any version on arm supports ghci.

**Comment by sebastiaanvisser** [comment]
Thanks for answering Neil. I can't say anything more about this, I never tried GHC on ARM and have no idea how that would impact Template Haskell and therefor `fclabels`.

**Comment by gohai** [comment]
Seems it only works on [7.10.2 + debian patches](https://www.reddit.com/r/haskell/comments/35bw0b/at_last_debian_unstable_has_working_arm_ghci_and/).

**Comment by hesselink** [comment]
I guess there's not much we can do about a compiler without TH support. Since it does work on the latest GHC, I'll close this one. Feel free to reopen if anyone disagrees.
