### ISSUE TITLE
GHC 8: Segmentation fault/access violation in generated code

### ISSUE THREAD

**Issue by Heather** [sebastiaanvisser/fclabels#27]
Preprocessing library fclabels-2.0.2.3...
[10 of 10] Compiling Data.Label.Base  ( src\Data\Label\Base.hs, dist\build\Data\Label\Base.o )
Segmentation fault/access violation in generated code
cabal: Error: some packages failed to install:
fclabels-2.0.2.3 failed during the building phase. The exception was:
ExitFailure 1

**Comment by bergmark** [comment]
How can I reproduce this? For me compilation fails because of template-haskell:

```
[ 4 of 10] Compiling Data.Label.Derive ( src/Data/Label/Derive.hs, dist/dist-sandbox-a2140f1b/build/Data/Label/Derive.o )

src/Data/Label/Derive.hs:205:7: error:
    • The constructor ‘DataD’ should have 6 arguments, but has been given 5
    • In the pattern: DataD ctx nm vars cs ns
      In a case alternative:
          DataD ctx nm vars cs ns -> DataD ctx nm vars (con <$> cs) ns
      In the expression:
        case dec of {
          DataD ctx nm vars cs ns -> DataD ctx nm vars (con <$> cs) ns
          NewtypeD ctx nm vars c ns -> NewtypeD ctx nm vars (con c) ns
          rest -> rest }

src/Data/Label/Derive.hs:275:13: error:
    • The constructor ‘DataD’ should have 6 arguments, but has been given 5
    • In the pattern: DataD _ n vs cs _
      In a case alternative: DataD _ n vs cs _ -> (n, cs, vs)
      In the expression:
        case dec of {
          DataD _ n vs cs _ -> (n, cs, vs)
          NewtypeD _ n vs c _ -> (n, [c], vs)
          _ -> fclError
                 "Can only derive labels for datatypes and newtypes." }
Failed to install fclabels-2.0.2.3
cabal: Error: some packages failed to install:
fclabels-2.0.2.3 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by Heather** [comment]
@bergmark I've used master version of template haskell, can't really deduce what is happening

**Comment by bergmark** [comment]
I'll try some more later today, if this is a regression in ghc we should report it quickly.

**Comment by Heather** [comment]
@bergmark though there are few known blockers in current ghc 8 RC I didn't dig much

**Comment by asr** [comment]
Ping.

**Comment by hesselink** [comment]
@asr What exactly are you looking for?

**Comment by bergmark** [comment]
@phadej managed to compile the ghc8 branch (on ghc8!) without problems.

**Comment by phadej** [comment]
I'd recommend generating `.travis.yml` with https://github.com/hvr/multi-ghc-travis/blob/master/make_travis_yml.hs, it has ghc8.0.0-rc1 there as well. I can make a PR.

**Comment by bergmark** [comment]
I completely forgot about travis yesterday. Please send a PR, that'd be great!

**Comment by asr** [comment]
> @asr What exactly are you looking for?

I should have written something like 'I am following this issue because Agda requires the missing support for GHC 8'.

**Comment by hesselink** [comment]
I've just released fclabels 2.0.3 with GHC 8 support. @Heather Can you check if your problem has been fixed?

**Comment by Heather** [comment]
@hesselink no, currently can, testing environment is gone

**Comment by hesselink** [comment]
OK, then I'll assume that it's fixed since it works for me and on travis. Feel free to reopen if it turns out it's still happening.
