### ISSUE TITLE
Test suite failures on ghc < 7.6

### ISSUE THREAD

**Issue by bergmark** [sebastiaanvisser/fclabels#29]
Can be seen here: https://travis-ci.org/sebastiaanvisser/fclabels/builds/103617479

**Comment by hesselink** [comment]
I'm not sure if this has ever been made explicit, but I thought the goal was always to support three releases. That would now be 7.6 - 7.10. More support would be nice, of course, but also more work (especially wrt. template haskell).

**Comment by bergmark** [comment]
I was not aware of that. Then we should perhaps decide how broken the earlier versions are and if we should edit in some lower bounds.

**Comment by hesselink** [comment]
I think it was mostly because this is what other packages tend to do as well. It's also not a very active thing, so this might be a good moment to consider what's the right thing to do.

**Comment by bergmark** [comment]
Fixed the 7.4 build. The 7.2 build failed and I couldn't tell why...if anyone is interested in fixing that please give it a try.
