### ISSUE TITLE
Support GHC 8.0

### ISSUE THREAD

**Issue by ndmitchell** [sebastiaanvisser/fclabels#31]
GHC 8.0 RC2 ships with template-haskell-2.11.0.0. You have the constraint template-haskell >= 2.2 && < 2.11. Needs loosening to allow installing.

I note you have tested-with GHC==8.0.1, so this might be a late-in-the-day bounds bump from template-haskell.

**Comment by ndmitchell** [comment]
Looks like #30 will fix this.

**Comment by hesselink** [comment]
I've just released fclabels-2.0.3 with GHC 8 support.
