### ISSUE TITLE
fclabels-2.0.3.3 build hangs on ghc-8.6.3/cabal-2.4.1.0 under Windows 10

### ISSUE THREAD

**Issue by zornslemon** [sebastiaanvisser/fclabels#37]
When I try to build fclabels-2.0.3.3 under ghc-8.6.3 and cabal-2.4.1.0, ghc never finishes compiling Data.Label.Base. (Task manager shows it happily keeps working overnight, until killed.) (This is on Windows 10.)

[See output attached.](https://github.com/sebastiaanvisser/fclabels/files/2717777/fclabels_build_cabal_output.txt)[2]

No problem building fclabels-2.0.3.3 using ghc-8.4.4 and stack resolver lts-12.20. [This r/haskell reddit comment](https://www.reddit.com/r/haskell/comments/a1u9qj/monthly_hask_anything_december_2018/ech9ael) [1] indicates that ghc-8.6.2 and earlier versions successfully built fclabels-2.0.3.3 on Windows 10 also, and only had trouble when using ghc-8.6.3.

My use case is the same as in the reddit comment: I'm trying to build HIE on Windows 10. The 8.6.3 target for HIE uses stack resolver lts-13.0, but as I found the problem is the same when trying to build fclabels without stack, using cabal.

I'll stick with building using an earlier ghc but thought I should note the problem.

[1] https://www.reddit.com/r/haskell/comments/a1u9qj/monthly_hask_anything_december_2018/ech9ael
[2] [fclabels_build_cabal_output.txt](https://github.com/sebastiaanvisser/fclabels/files/2717777/fclabels_build_cabal_output.txt)

**Comment by sebastiaanvisser** [comment]
Thanks for reporting!

Haven't really been maintaining fclabels for a while now and having been doing a whole lot of serious Haskell lately. Not running on win10 myself, but might give this a look later on this week. Good reason for me to upgrade my stack/ghc/fclabels and hack a bit of Haskell.

**Comment by Anrock** [comment]
Probably it's this: https://ghc.haskell.org/trac/ghc/ticket/16057

**Comment by zornslemon** [comment]
Thanks for updates! The ghc ticket thread 

> Probably it's this: https://ghc.haskell.org/trac/ghc/ticket/16057

mentions a solution and possible 8.6.4 release which will fix the (ghc) problem. Wait and see seems sensible.

**Comment by Vlix** [comment]
I got this too. Tried to `stack install.hs hie-8.6.3` in the cloned `haskell-ide-engine` repo main folder. Let it run for a night, and still nothing happened.

Then tried `stack build haskell-lsp-types-0.8.0.1` (which was what was being tried when it failed, afaik) and it actually showed an error (instead of just never continuing):

```
C:\haskell-ide-engine>stack build haskell-lsp-types-0.8.0.1
haskell-lsp-types-0.8.0.1: configure
haskell-lsp-types-0.8.0.1: build

--  While building package haskell-lsp-types-0.8.0.1 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_2.4.0.1_ghc-8.6.3.exe --builddir=.stack-work\dist\e626a42b build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 11
    Logs have been written to: C:\haskell-ide-engine\.stack-work\logs\haskell-lsp-types-0.8.0.1.log

    Configuring haskell-lsp-types-0.8.0.1...
    Preprocessing library for haskell-lsp-types-0.8.0.1..
    Building library for haskell-lsp-types-0.8.0.1..
    [ 1 of 24] Compiling Language.Haskell.LSP.Types.Constants ( src\Language\Haskell\LSP\Types\Constants.hs, .stack-work\dist\e626a42b\build\Language\Haskell\LSP\Types\Constants.o )
    [ 2 of 24] Compiling Language.Haskell.LSP.Types.List ( src\Language\Haskell\LSP\Types\List.hs, .stack-work\dist\e626a42b\build\Language\Haskell\LSP\Types\List.o )
    [ 3 of 24] Compiling Language.Haskell.LSP.Types.DocumentFilter ( src\Language\Haskell\LSP\Types\DocumentFilter.hs, .stack-work\dist\e626a42b\build\Language\Haskell\LSP\Types\DocumentFilter.o )

    Access violation in generated code when reading 0xf3c895900

     Attempting to reconstruct a stack trace...

       Frame    Code address
     * 0x4cddae0        0x16d6f148 C:\sr\snapshots\61a81a1c\lib\x86_64-windows-ghc-8.6.3\aeson-1.4.2.0-FbeMPbY577250WvAyno7Sr\HSaeson-1.4.2.0-FbeMPbY577250WvAyno7Sr.o+0x2f040
                 (aesonzm1zi4zi2zi0zmFbeMPbY577250WvAyno7Sr_DataziAesonziTH_consToValue_info+0x688)

C:\haskell-ide-engine>
```

Maybe this'll help someone?

**Comment by Anrock** [comment]
Okay, 8.6.4 is release and fclabels buildable with it.

**Comment by giuliohome** [comment]
I have version `8.6.4` and I'm still stuck :-1: 

```haskell
C:\haskell\hrt\Comonad>stack ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 8.6.4

C:\haskell\hrt\Comonad>stack build
←[0mCabal-2.4.1.0: configure←[0m
←[0mCabal-2.4.1.0: build←[0m
Progress 0/5
```
